// Shared location data used by map.html and library.html
// ── Update the `year` field for each entry, then the sort below handles the rest.
const PHOTOS = [
  {
    title: 'Anacapa Island',
    location: 'California, USA',
    year: 2024,
    label: 'Anacapa Island, California',
    x: (-119.4 + 180) / 360, y: (90 - 34.0) / 180,
    thumb: 'thumbs/anacapa/mainArtboard 2_15.webp',
    canvas: 'canvas/anacapa.webp',
    images: [
      'thumbs/anacapa/imgi_66_DSC_8158.jpg',
      'thumbs/anacapa/imgi_84_DSC_8167.jpg',
      'thumbs/anacapa/imgi_89_DSC_8168.jpg',
      'thumbs/anacapa/imgi_132_DSC_8157.jpg',
      'thumbs/anacapa/imgi_138_DSC_8153.jpg',
      'thumbs/anacapa/imgi_149_DSC_8161.jpg',
    ],
    photos: [
      'thumbs/anacapa/imgi_66_DSC_8158.jpg',
      'thumbs/anacapa/imgi_84_DSC_8167.jpg',
      'thumbs/anacapa/imgi_89_DSC_8168.jpg',
      'thumbs/anacapa/imgi_132_DSC_8157.jpg',
      'thumbs/anacapa/imgi_138_DSC_8153.jpg',
      'thumbs/anacapa/imgi_149_DSC_8161.jpg',
      'thumbs/anacapa/imgi_155_DSC_8170.jpg',
      'thumbs/anacapa/imgi_162_DSC_8154.jpg',
      'thumbs/anacapa/imgi_168_DSC_8151.jpg',
    ],
    url: 'anacapa.html'
  },
  {
    title: 'Antigua',
    location: 'Guatemala',
    year: 2023,
    label: 'Antigua',
    x: (-61.8 + 180) / 360, y: (90 - 17.1) / 180,
    thumb: 'thumbs/antigua/mainArtboard 2_7.webp',
    canvas: 'canvas/antigua.webp',
    hideCanvas: true,
    images: [
      'thumbs/antigua/imgi_20_guate-12.jpg',
      'thumbs/antigua/imgi_25_guate-14.jpg',
      'thumbs/antigua/imgi_32_guate-11.jpg',
      'thumbs/antigua/imgi_38_guate-8.jpg',
      'thumbs/antigua/imgi_44_guate-10.jpg',
      'thumbs/antigua/imgi_49_guate-3.jpg',
    ],
    photos: [
      'thumbs/antigua/imgi_20_guate-12.jpg',
      'thumbs/antigua/imgi_25_guate-14.jpg',
      'thumbs/antigua/imgi_32_guate-11.jpg',
      'thumbs/antigua/imgi_38_guate-8.jpg',
      'thumbs/antigua/imgi_44_guate-10.jpg',
      'thumbs/antigua/imgi_49_guate-3.jpg',
      'thumbs/antigua/imgi_55_guate-6.jpg',
    ],
    url: 'antigua.html'
  },
  {
    title: 'Bocas del Toro',
    location: 'Panama',
    year: 2024,
    label: 'Bocas del Toro, Panama',
    x: (-82.2 + 180) / 360, y: (90 - 9.3) / 180,
    thumb: 'thumbs/bocas del toro/mainArtboard 2_12.webp',
    canvas: 'canvas/red-frog.webp',
    hideCanvas: true,
    images: [
      'thumbs/bocas del toro/imgi_37_bxb-21.jpg',
      'thumbs/bocas del toro/imgi_52_bxb-26.jpg',
      'thumbs/bocas del toro/imgi_57_bxb-32.jpg',
      'thumbs/bocas del toro/imgi_87_bxb-28.jpg',
      'thumbs/bocas del toro/imgi_93_bxb-27.jpg',
      'thumbs/bocas del toro/imgi_105_bxb-24.jpg',
    ],
    photos: [
      'thumbs/bocas del toro/imgi_37_bxb-21.jpg',
      'thumbs/bocas del toro/imgi_52_bxb-26.jpg',
      'thumbs/bocas del toro/imgi_57_bxb-32.jpg',
      'thumbs/bocas del toro/imgi_87_bxb-28.jpg',
      'thumbs/bocas del toro/imgi_93_bxb-27.jpg',
      'thumbs/bocas del toro/imgi_105_bxb-24.jpg',
      'thumbs/bocas del toro/imgi_123_bxb-14.jpg',
      'thumbs/bocas del toro/imgi_129_bxb-10.jpg',
      'thumbs/bocas del toro/imgi_136_bxb-2.jpg',
      'thumbs/bocas del toro/imgi_141_bxb-7.jpg',
      'thumbs/bocas del toro/imgi_147_bxb-12.jpg',
      'thumbs/bocas del toro/imgi_153_surf-5.jpg',
      'thumbs/bocas del toro/imgi_160_bxb.jpg',
    ],
    url: 'bocas-del-toro.html'
  },
  {
    title: 'Chobe',
    location: 'Botswana',
    year: 2025,
    label: 'Chobe, Botswana',
    x: (24.5 + 180) / 360, y: (90 - (-18.0)) / 180,
    thumb: 'thumbs/botswana/mainArtboard 2_4.webp',
    canvas: 'canvas/chobe.webp',
    // images: first 6 used for map-view spread fan
    images: [
      'thumbs/botswana/imgi_82_DSC04306.jpg',
      'thumbs/botswana/imgi_83_DSC04253.jpg',
      'thumbs/botswana/imgi_84_DSC04240.jpg',
      'thumbs/botswana/imgi_86_DSC04282.jpg',
      'thumbs/botswana/imgi_87_DSC04246.jpg',
      'thumbs/botswana/imgi_91_DSC04258.jpg',
    ],
    // photos: full set used for library reel
    photos: [
      'thumbs/botswana/imgi_82_DSC04306.jpg', 'thumbs/botswana/gif-0415-1.gif',
      'thumbs/botswana/imgi_83_DSC04253.jpg',
      'thumbs/botswana/imgi_84_DSC04240.jpg', 'thumbs/botswana/gif-0415.gif',
      'thumbs/botswana/imgi_86_DSC04282.jpg',
      'thumbs/botswana/imgi_87_DSC04246.jpg',
      'thumbs/botswana/imgi_91_DSC04258.jpg',
      'thumbs/botswana/imgi_94_DSC04243.jpg',
      'thumbs/botswana/imgi_95_DSC04233.jpg',
      'thumbs/botswana/imgi_96_DSC04204.jpg',
      'thumbs/botswana/imgi_101_DSC04369.jpg',
      'thumbs/botswana/imgi_104_DSC04357.jpg',
      'thumbs/botswana/imgi_110_DSC04078.jpg',
      'thumbs/botswana/imgi_113_DSC04010.jpg',
      'thumbs/botswana/imgi_139_DSC04285.jpg',
    ],
    url: 'botswana.html'
  },
  {
    title: 'Cairo',
    location: 'Egypt',
    year: 2025,
    label: 'Cairo, Egypt',
    x: (31.2 + 180) / 360, y: (90 - 30.0) / 180,
    thumb: 'thumbs/cairo/mainArtboard 2_5.webp',
    canvas: 'canvas/cairo.webp',
    images: [
      'thumbs/cairo/imgi_38_DSC03663.jpg',
      'thumbs/cairo/imgi_44_DSC03695.jpg',
      'thumbs/cairo/imgi_49_DSC03659.jpg',
      'thumbs/cairo/imgi_56_DSC03643.jpg',
      'thumbs/cairo/imgi_62_DSC03653.jpg',
      'thumbs/cairo/imgi_68_DSC03651.jpg',
    ],
    photos: [
      'thumbs/cairo/imgi_38_DSC03663.jpg',
      'thumbs/cairo/imgi_49_DSC03659.jpg',
      'thumbs/cairo/imgi_56_DSC03643.jpg',
      'thumbs/cairo/gif_0415.gif',
      'thumbs/cairo/imgi_79_DSC03713.jpg',
      'thumbs/cairo/imgi_92_DSC03698.jpg',
      'thumbs/cairo/imgi_110_DSC03727.jpg',
    ],
    url: 'cairo.html'
  },
  {
    title: 'Cusco',
    location: 'Peru',
    year: 2026,
    label: 'Cusco, Peru',
    x: (-71.9 + 180) / 360, y: (90 - (-13.5)) / 180,
    thumb: 'thumbs/cusco/mainArtboard 2_14.webp',
    images: [
      'thumbs/cusco/DSC07258.jpg',
      'thumbs/cusco/DSC07262.jpg',
      'thumbs/cusco/DSC07263.jpg',
      'thumbs/cusco/DSC07266.jpg',
      'thumbs/cusco/DSC07278.jpg',
      'thumbs/cusco/DSC07291.jpg',
    ],
    photos: [
      'thumbs/cusco/DSC07258.jpg',
      'thumbs/cusco/DSC07262.jpg',
      'thumbs/cusco/DSC07263.jpg',
      'thumbs/cusco/DSC07266.jpg',
      'thumbs/cusco/DSC07278.jpg',
      'thumbs/cusco/DSC07291.jpg',
      'thumbs/cusco/DSC07296.jpg',
      'thumbs/cusco/DSC07298.jpg',
      'thumbs/cusco/DSC07300.jpg',
      'thumbs/cusco/DSC07301.jpg',
      'thumbs/cusco/DSC07304.jpg',
      'thumbs/cusco/DSC07311.jpg',
      'thumbs/cusco/DSC07316.jpg',
      'thumbs/cusco/DSC07322.jpg',
      'thumbs/cusco/DSC07339.jpg',
      'thumbs/cusco/DSC07346.jpg',
    ],
    url: 'cusco.html'
  },
  {
    title: 'Guanacaste',
    location: 'Costa Rica',
    year: 2025,
    label: 'Guanacaste, Costa Rica',
    x: (-85.5 + 180) / 360, y: (90 - 10.5) / 180,
    thumb: 'thumbs/guanacaste/mainArtboard 7_20.webp',
    canvas: 'canvas/guanacaste.webp',
    images: [
      'thumbs/guanacaste/imgi_45_DSC_6313.jpg',
      'thumbs/guanacaste/imgi_51_DSC_6335.jpg',
      'thumbs/guanacaste/imgi_57_DSC_6403.jpg',
      'thumbs/guanacaste/imgi_63_DSC_6466.jpg',
      'thumbs/guanacaste/imgi_69_DSC_6344.jpg',
      'thumbs/guanacaste/imgi_75_DSC_6481+copy.jpg',
    ],
    photos: [
      'thumbs/guanacaste/imgi_45_DSC_6313.jpg',
      'thumbs/guanacaste/imgi_51_DSC_6335.jpg',
      'thumbs/guanacaste/imgi_57_DSC_6403.jpg',
      'thumbs/guanacaste/imgi_63_DSC_6466.jpg',
      'thumbs/guanacaste/imgi_69_DSC_6344.jpg',
      'thumbs/guanacaste/imgi_75_DSC_6481+copy.jpg',
      'thumbs/guanacaste/imgi_87_DSC_6378.jpg',
      'thumbs/guanacaste/imgi_93_DSC_6410.jpg',
      'thumbs/guanacaste/imgi_99_DSC_6294.jpg',
      'thumbs/guanacaste/imgi_111_DSC_6365.jpg',
      'thumbs/guanacaste/imgi_117_DSC_6428.jpg',
      'thumbs/guanacaste/imgi_123_DSC_6293.jpg',
      'thumbs/guanacaste/imgi_129_DSC_6350.jpg',
      'thumbs/guanacaste/imgi_141_DSC_6287.jpg',
      'thumbs/guanacaste/imgi_153_DSC_6289.jpg',
    ],
    url: 'guanacaste.html'
  },
  {
    title: 'Hà Giang',
    location: 'Vietnam',
    year: 2025,
    label: 'Hà Giang, Vietnam',
    x: (105.0 + 180) / 360, y: (90 - 23.0) / 180,
    thumb: 'thumbs/ha giang/mainArtboard 2_9.webp',
    canvas: 'canvas/ha-giang.webp',
    hideCanvas: true,
    images: [
      'thumbs/ha giang/imgi_53_DSC02067.jpg',
      'thumbs/ha giang/imgi_59_DSC02134.jpg',
      'thumbs/ha giang/imgi_65_DSC02073.jpg',
      'thumbs/ha giang/imgi_71_DSC02137.jpg',
      'thumbs/ha giang/imgi_77_DSC01994.jpg',
      'thumbs/ha giang/imgi_84_DSC01995.jpg',
    ],
    photos: [
      'thumbs/ha giang/imgi_53_DSC02067.jpg',
      'thumbs/ha giang/imgi_59_DSC02134.jpg',
      'thumbs/ha giang/imgi_65_DSC02073.jpg',
      'thumbs/ha giang/imgi_71_DSC02137.jpg',
      'thumbs/ha giang/imgi_77_DSC01994.jpg',
      'thumbs/ha giang/imgi_84_DSC01995.jpg',
      'thumbs/ha giang/imgi_90_DSC02026.jpg',
      'thumbs/ha giang/imgi_98_DSC02119.jpg',
      'thumbs/ha giang/imgi_105_DSC02123.jpg',
      'thumbs/ha giang/imgi_112_DSC02133.jpg',
      'thumbs/ha giang/imgi_126_DSC02138.jpg',
      'thumbs/ha giang/imgi_147_DSC02141.jpg',
      'thumbs/ha giang/imgi_161_DSC02006.jpg',
      'thumbs/ha giang/imgi_168_DSC02009.jpg',
      'thumbs/ha giang/imgi_174_DSC01965.jpg',
      'thumbs/ha giang/imgi_188_DSC01977.jpg',
      'thumbs/ha giang/imgi_195_DSC01991.jpg',
      'thumbs/ha giang/imgi_209_DSC02066.jpg',
      'thumbs/ha giang/imgi_216_DSC02076.jpg',
    ],
    url: 'ha-giang.html'
  },
  {
    title: 'Hanoi',
    location: 'Vietnam',
    year: 2025,
    label: 'Hanoi, Vietnam',
    x: (105.8 + 180) / 360, y: (90 - 21.0) / 180,
    thumb: 'thumbs/hanoi/mainArtboard 2.webp',
    canvas: 'canvas/hanoi.webp',
    hideCanvas: true,
    images: [
      'thumbs/hanoi/imgi_88_DSC01859.jpg',
      'thumbs/hanoi/imgi_94_DSC01851.jpg',
      'thumbs/hanoi/imgi_99_DSC01856.jpg',
      'thumbs/hanoi/imgi_105_DSC01835.jpg',
      'thumbs/hanoi/imgi_111_DSC01826.jpg',
      'thumbs/hanoi/imgi_117_DSC01844.jpg',
    ],
    photos: [
      'thumbs/hanoi/imgi_88_DSC01859.jpg',
      'thumbs/hanoi/imgi_94_DSC01851.jpg', 'thumbs/hanoi/gif-0415.gif',
      'thumbs/hanoi/imgi_99_DSC01856.jpg',
      'thumbs/hanoi/imgi_105_DSC01835.jpg', 'thumbs/hanoi/gif-0415-1.gif',
      'thumbs/hanoi/imgi_111_DSC01826.jpg', 'thumbs/hanoi/gif-0415-2.gif',
      'thumbs/hanoi/imgi_117_DSC01844.jpg',
      'thumbs/hanoi/imgi_123_DSC01849.jpg', 'thumbs/hanoi/gif-0415-3.gif',
      'thumbs/hanoi/imgi_130_DSC01861.jpg',
      'thumbs/hanoi/imgi_136_DSC01865.jpg',
      'thumbs/hanoi/imgi_142_DSC01871.jpg',
      'thumbs/hanoi/imgi_153_DSC01839.jpg',
      'thumbs/hanoi/imgi_160_DSC01838.jpg',
      'thumbs/hanoi/imgi_165_DSC01836.jpg',
      'thumbs/hanoi/imgi_171_DSC01809.jpg',
      'thumbs/hanoi/imgi_177_DSC01811.jpg',
      'thumbs/hanoi/imgi_183_DSC01817.jpg',
      'thumbs/hanoi/imgi_273_DSC01723.jpg',
      'thumbs/hanoi/imgi_291_DSC01728.jpg',
      'thumbs/hanoi/imgi_298_DSC01744.jpg',
      'thumbs/hanoi/imgi_304_DSC01753.jpg',
      'thumbs/hanoi/imgi_309_DSC01755.jpg',
      'thumbs/hanoi/imgi_322_DSC01782.jpg',
      'thumbs/hanoi/imgi_328_DSC01784.jpg',
    ],
    url: 'hanoi.html'
  },
  {
    title: 'Golden Circle',
    location: 'Iceland',
    year: 2017,
    label: 'Iceland',
    x: (-18.0 + 180) / 360, y: (90 - 65.0) / 180,
    thumb: 'thumbs/iceland/mainArtboard 2_6.webp',
    canvas: 'canvas/iceland.webp',
    images: [
      'thumbs/iceland/imgi_78_6-full.jpg',
      'thumbs/iceland/imgi_90_1-full.jpg',
      'thumbs/iceland/imgi_96_9-full.jpg',
      'thumbs/iceland/imgi_102_3-full.jpg',
      'thumbs/iceland/imgi_108_4-full.jpg',
      'thumbs/iceland/imgi_114_5-full.jpg',
    ],
    photos: [
      'thumbs/iceland/imgi_78_6-full.jpg',
      'thumbs/iceland/imgi_90_1-full.jpg',
      'thumbs/iceland/imgi_96_9-full.jpg',
      'thumbs/iceland/imgi_102_3-full.jpg',
      'thumbs/iceland/imgi_108_4-full.jpg',
      'thumbs/iceland/imgi_114_5-full.jpg',
      'thumbs/iceland/imgi_120_7-full.jpg',
      'thumbs/iceland/imgi_126_8-full.jpg',
      'thumbs/iceland/imgi_221_11-full.jpg',
      'thumbs/iceland/imgi_228_10-full.jpg',
      'thumbs/iceland/imgi_234_13-full.jpg',
      'thumbs/iceland/imgi_240_icelnd-5.jpg',
      'thumbs/iceland/imgi_254_icelnd-32.jpg',
      'thumbs/iceland/imgi_261_icelnd-168.jpg',
      'thumbs/iceland/imgi_268_icelnd-75.jpg',
      'thumbs/iceland/imgi_275_icelnd-107.jpg',
      'thumbs/iceland/imgi_282_icelnd-185.jpg',
      'thumbs/iceland/imgi_289_icelnd-219.jpg',
      'thumbs/iceland/imgi_296_icelnd-175.jpg',
      'thumbs/iceland/imgi_303_icelnd-116.jpg',
      'thumbs/iceland/imgi_310_icelnd-54.jpg',
      'thumbs/iceland/imgi_317_icelnd-52.jpg',
      'thumbs/iceland/imgi_324_icelnd-50.jpg',
      'thumbs/iceland/imgi_331_icelnd-36.jpg',
      'thumbs/iceland/imgi_338_icelnd-41.jpg',
      'thumbs/iceland/imgi_345_icelnd-44.jpg',
      'thumbs/iceland/imgi_352_icelnd-37.jpg',
    ],
    url: 'iceland.html'
  },
  {
    title: 'Manuel Antonio',
    location: 'Costa Rica',
    year: 2018,
    label: 'Manuel Antonio, Costa Rica',
    x: (-84.2 + 180) / 360, y: (90 - 9.4) / 180,
    thumb: 'thumbs/manuel antonio/mainArtboard 8.webp',
    canvas: 'canvas/manuel-antonio.webp',
    images: [
      'thumbs/manuel antonio/imgi_19_3-full.jpg',
      'thumbs/manuel antonio/imgi_25_1-full.jpg',
      'thumbs/manuel antonio/imgi_32_5-full.jpg',
      'thumbs/manuel antonio/imgi_37_10-full.jpg',
      'thumbs/manuel antonio/imgi_43_6-full.jpg',
      'thumbs/manuel antonio/imgi_49_8-full.jpg',
    ],
    photos: [
      'thumbs/manuel antonio/imgi_19_3-full.jpg',
      'thumbs/manuel antonio/imgi_25_1-full.jpg',
      'thumbs/manuel antonio/imgi_32_5-full.jpg',
      'thumbs/manuel antonio/imgi_37_10-full.jpg',
      'thumbs/manuel antonio/imgi_43_6-full.jpg',
      'thumbs/manuel antonio/imgi_49_8-full.jpg',
      'thumbs/manuel antonio/imgi_57_4-full.jpg',
      'thumbs/manuel antonio/imgi_64_9-full.jpg',
    ],
    url: 'manuel-antonio.html'
  },
  {
    title: 'Narai-juku',
    location: 'Japan',
    year: 2023,
    label: 'Narai-juku, Japan',
    x: (137.9 + 180) / 360, y: (90 - 36.0) / 180,
    thumb: 'thumbs/narai juku/mainArtboard 9.webp',
    canvas: 'canvas/narai-juku.webp',
    hideCanvas: true,
    images: [
      'thumbs/narai juku/imgi_64_japan-36.jpg',
      'thumbs/narai juku/imgi_69_japan-60.jpg',
      'thumbs/narai juku/imgi_76_japan-37.jpg',
      'thumbs/narai juku/imgi_81_japan-62.jpg',
      'thumbs/narai juku/imgi_88_japan-43.jpg',
      'thumbs/narai juku/imgi_93_japan-52.jpg',
    ],
    photos: [
      'thumbs/narai juku/imgi_64_japan-36.jpg',
      'thumbs/narai juku/imgi_69_japan-60.jpg',
      'thumbs/narai juku/imgi_76_japan-37.jpg',
      'thumbs/narai juku/imgi_81_japan-62.jpg',
      'thumbs/narai juku/imgi_88_japan-43.jpg',
      'thumbs/narai juku/imgi_93_japan-52.jpg',
      'thumbs/narai juku/imgi_100_japan-45.jpg',
      'thumbs/narai juku/imgi_105_japan-53.jpg',
      'thumbs/narai juku/imgi_117_japan-54.jpg',
      'thumbs/narai juku/imgi_123_japan-47.jpg',
      'thumbs/narai juku/imgi_129_japan-56.jpg',
      'thumbs/narai juku/imgi_142_japan-57.jpg',
      'thumbs/narai juku/imgi_148_japan-49.jpg',
      'thumbs/narai juku/imgi_153_japan-73.jpg',
      'thumbs/narai juku/imgi_160_japan-55.jpg',
      'thumbs/narai juku/imgi_165_japan-61.jpg',
      'thumbs/narai juku/imgi_183_japan-58.jpg',
    ],
    url: 'narai-juku.html'
  },
  {
    title: 'Nepal',
    location: 'Nepal',
    year: 2025,
    label: 'Nepal',
    x: (85.3 + 180) / 360, y: (90 - 27.7) / 180,
    thumb: 'thumbs/nepal/mainArtboard 2_13.webp',
    canvas: 'canvas/nepal.webp',
    hideCanvas: true,
    images: [
      'thumbs/nepal/imgi_51_DSC03151.jpg',
      'thumbs/nepal/imgi_57_DSC03218.jpg',
      'thumbs/nepal/imgi_63_DSC03234.jpg',
      'thumbs/nepal/imgi_99_DSC02841.jpg',
      'thumbs/nepal/imgi_159_DSC03092.jpg',
      'thumbs/nepal/imgi_111_DSC02851.jpg',
    ],
    photos: [
      'thumbs/nepal/gif-0415-1.gif',
      'thumbs/nepal/imgi_51_DSC03151.jpg',
      'thumbs/nepal/imgi_57_DSC03218.jpg',
      'thumbs/nepal/imgi_63_DSC03234.jpg',
      'thumbs/nepal/imgi_99_DSC02841.jpg',
      'thumbs/nepal/imgi_111_DSC02851.jpg',
      'thumbs/nepal/imgi_135_DSC02967.jpg', 'thumbs/nepal/gif-0415-2.gif',
      'thumbs/nepal/imgi_141_DSC02982.jpg',
      'thumbs/nepal/imgi_153_DSC03075.jpg',
      'thumbs/nepal/imgi_171_DSC03102.jpg',
    ],
    url: 'nepal.html'
  },
  {
    title: 'Nusa Penida',
    location: 'Indonesia',
    year: 2025,
    label: 'Nusa Penida, Indonesia',
    x: (115.5 + 180) / 360, y: (90 - (-8.7)) / 180,
    thumb: 'thumbs/nusa penida/mainArtboard 2_10.webp',
    canvas: 'canvas/nusa-penida.webp',
    images: [
      'thumbs/nusa penida/imgi_19_DSC02412.jpg',
      'thumbs/nusa penida/imgi_25_DSC02349.jpg',
      'thumbs/nusa penida/imgi_31_DSC02354.jpg',
      'thumbs/nusa penida/imgi_37_DSC02411.jpg',
      'thumbs/nusa penida/imgi_43_DSC02434.jpg',
      'thumbs/nusa penida/imgi_49_DSC02430.jpg',
    ],
    photos: [
      'thumbs/nusa penida/imgi_19_DSC02412.jpg', 'thumbs/nusa penida/gif-0415-2.gif',
      'thumbs/nusa penida/imgi_25_DSC02349.jpg',
      'thumbs/nusa penida/imgi_31_DSC02354.jpg', 'thumbs/nusa penida/gif-0415.gif',
      'thumbs/nusa penida/imgi_37_DSC02411.jpg',
      'thumbs/nusa penida/imgi_43_DSC02434.jpg',
      'thumbs/nusa penida/imgi_49_DSC02430.jpg', 'thumbs/nusa penida/gif-0415-1.gif',
      'thumbs/nusa penida/imgi_56_DSC02304.jpg',
      'thumbs/nusa penida/imgi_63_DSC02370.jpg',
    ],
    url: 'nusa-penida.html'
  },
  {
    title: 'Salento',
    location: 'Colombia',
    year: 2026,
    label: 'Salento, Colombia',
    x: (-75.6 + 180) / 360, y: (90 - 4.6) / 180,
    thumb: 'thumbs/salento/mainArtboard 10.webp',
    hideCanvas: true,
    images: [
      'thumbs/salento/DSC06961.jpg',
      'thumbs/salento/DSC06971.jpg',
      'thumbs/salento/DSC06974.jpg',
      'thumbs/salento/DSC06986.jpg',
      'thumbs/salento/DSC06999.jpg',
      'thumbs/salento/DSC07069.jpg',
    ],
    photos: [
      'thumbs/salento/DSC06961.jpg',
      'thumbs/salento/DSC06971.jpg',
      'thumbs/salento/DSC06974.jpg',
      'thumbs/salento/DSC06986.jpg',
      'thumbs/salento/DSC06999.jpg',
      'thumbs/salento/DSC07069.jpg',
      'thumbs/salento/DSC07076.jpg',
      'thumbs/salento/DSC07088.jpg',
      'thumbs/salento/DSC07110.jpg',
      'thumbs/salento/DSC07114.jpg',
      'thumbs/salento/DSC07123.jpg',
      'thumbs/salento/DSC07125.jpg',
    ],
    url: 'salento.html'
  },
  {
    title: 'Sequoia',
    location: 'California, USA',
    year: 2025,
    label: 'Sequoia National Park',
    x: (-118.7 + 180) / 360, y: (90 - 36.4) / 180,
    thumb: 'thumbs/sequoias/mainArtboard 2_2.webp',
    canvas: 'canvas/sequoias.webp',
    hideCanvas: true,
    images: [
      'thumbs/sequoias/imgi_21_7-full.jpg',
      'thumbs/sequoias/imgi_27_9-full.jpg',
      'thumbs/sequoias/imgi_33_6-full.jpg',
      'thumbs/sequoias/imgi_39_11-full.jpg',
      'thumbs/sequoias/imgi_45_4-full.jpg',
      'thumbs/sequoias/imgi_51_1-full.jpg',
    ],
    photos: [
      'thumbs/sequoias/imgi_21_7-full.jpg',
      'thumbs/sequoias/imgi_27_9-full.jpg',
      'thumbs/sequoias/imgi_33_6-full.jpg',
      'thumbs/sequoias/imgi_39_11-full.jpg',
      'thumbs/sequoias/imgi_45_4-full.jpg',
      'thumbs/sequoias/imgi_51_1-full.jpg',
      'thumbs/sequoias/imgi_57_5-full.jpg',
      'thumbs/sequoias/imgi_63_10-full.jpg',
    ],
    url: 'sequoia.html'
  },
  {
    title: 'Southern France',
    location: 'France',
    year: 2017,
    label: 'Southern France',
    x: (5.5 + 180) / 360, y: (90 - 43.7) / 180,
    thumb: 'thumbs/southern france/mainArtboard 2_1.webp',
    canvas: 'canvas/southern-france.webp',
    images: [
      'thumbs/southern france/imgi_32_8-full.jpg',
      'thumbs/southern france/imgi_38_7-full.jpg',
      'thumbs/southern france/imgi_44_12-full.jpg',
      'thumbs/southern france/imgi_50_15-full.jpg',
      'thumbs/southern france/imgi_56_1-full.jpg',
      'thumbs/southern france/imgi_62_4-full.jpg',
    ],
    photos: [
      'thumbs/southern france/imgi_32_8-full.jpg',
      'thumbs/southern france/imgi_38_7-full.jpg', 'thumbs/southern france/gif-0415.gif',
      'thumbs/southern france/imgi_44_12-full.jpg',
      'thumbs/southern france/imgi_50_15-full.jpg', 'thumbs/southern france/gif-0415-1.gif',
      'thumbs/southern france/imgi_56_1-full.jpg',
      'thumbs/southern france/imgi_62_4-full.jpg',
      'thumbs/southern france/imgi_70_2-full.jpg',
      'thumbs/southern france/imgi_77_5-full.jpg',
      'thumbs/southern france/imgi_84_13-full.jpg',
      'thumbs/southern france/imgi_90_6-full.jpg',
      'thumbs/southern france/imgi_98_17-full.jpg',
      'thumbs/southern france/imgi_105_11-full.jpg',
      'thumbs/southern france/imgi_112_16-full.jpg',
    ],
    url: 'southern-france.html'
  },
  {
    title: 'Bangkok',
    location: 'Thailand',
    year: 2025,
    label: 'Bangkok, Thailand',
    x: (100.5 + 180) / 360, y: (90 - 13.75) / 180,
    thumb: 'thumbs/bangkok/imgi_22_DSC01108.jpg',
    canvas: 'canvas/bangkok.webp',
    hideCanvas: true,
    images: [
      'thumbs/bangkok/imgi_22_DSC01108.jpg',
      'thumbs/bangkok/imgi_27_DSC01021.jpg',
      'thumbs/bangkok/imgi_34_DSC01035.jpg',
      'thumbs/bangkok/imgi_40_DSC01055.jpg',
      'thumbs/bangkok/imgi_46_DSC01057.jpg',
      'thumbs/bangkok/imgi_52_DSC01103.jpg',
    ],
    photos: [
      'thumbs/bangkok/imgi_22_DSC01108.jpg',
      'thumbs/bangkok/imgi_27_DSC01021.jpg',
      'thumbs/bangkok/imgi_34_DSC01035.jpg',
      'thumbs/bangkok/imgi_40_DSC01055.jpg',
      'thumbs/bangkok/imgi_46_DSC01057.jpg',
      'thumbs/bangkok/imgi_52_DSC01103.jpg',
      'thumbs/bangkok/imgi_58_DSC01029.jpg',
      'thumbs/bangkok/imgi_64_DSC01109.jpg',
    ],
    url: 'bangkok.html'
  },
  {
    title: 'Gulf Islands',
    location: 'Thailand',
    year: 2019,
    label: 'Gulf Islands, Thailand',
    x: (100.1 + 180) / 360, y: (90 - 9.5) / 180,
    thumb: 'thumbs/gulf islands/imgi_28_2-full.jpg',
    canvas: 'canvas/gulf-islands.webp',
    hideCanvas: true,
    images: [
      'thumbs/gulf islands/imgi_28_2-full.jpg',
      'thumbs/gulf islands/imgi_34_3-full.jpg',
      'thumbs/gulf islands/imgi_39_5-full.jpg',
      'thumbs/gulf islands/imgi_46_7-full.jpg',
      'thumbs/gulf islands/imgi_52_6-full.jpg',
      'thumbs/gulf islands/imgi_58_11-full.jpg',
    ],
    photos: [
      'thumbs/gulf islands/imgi_28_2-full.jpg',
      'thumbs/gulf islands/imgi_34_3-full.jpg',
      'thumbs/gulf islands/imgi_39_5-full.jpg',
      'thumbs/gulf islands/imgi_46_7-full.jpg',
      'thumbs/gulf islands/imgi_52_6-full.jpg',
      'thumbs/gulf islands/imgi_58_11-full.jpg',
      'thumbs/gulf islands/imgi_64_8-full.jpg',
      'thumbs/gulf islands/imgi_70_1-full.jpg',
      'thumbs/gulf islands/imgi_75_9-full.jpg',
      'thumbs/gulf islands/imgi_82_10-full.jpg',
      'thumbs/gulf islands/imgi_88_4-full.jpg',
    ],
    url: 'gulf-islands.html'
  },
  {
    title: 'Khao Sok',
    location: 'Thailand',
    year: 2025,
    label: 'Khao Sok, Thailand',
    x: (98.5 + 180) / 360, y: (90 - 8.9) / 180,
    thumb: 'thumbs/khao sok/imgi_34_DSC01144.jpg',
    canvas: 'canvas/khao-sok.webp',
    hideCanvas: true,
    images: [
      'thumbs/khao sok/imgi_34_DSC01144.jpg',
      'thumbs/khao sok/imgi_40_DSC01132.jpg',
      'thumbs/khao sok/imgi_46_DSC01135.jpg',
      'thumbs/khao sok/imgi_51_DSC01129.jpg',
      'thumbs/khao sok/imgi_58_DSC01189.jpg',
      'thumbs/khao sok/imgi_64_DSC01247.jpg',
    ],
    photos: [
      'thumbs/khao sok/imgi_34_DSC01144.jpg',
      'thumbs/khao sok/imgi_40_DSC01132.jpg',
      'thumbs/khao sok/imgi_46_DSC01135.jpg',
      'thumbs/khao sok/imgi_51_DSC01129.jpg',
      'thumbs/khao sok/imgi_58_DSC01189.jpg',
      'thumbs/khao sok/imgi_64_DSC01247.jpg',
      'thumbs/khao sok/imgi_70_DSC01212.jpg',
      'thumbs/khao sok/imgi_81_DSC01276.jpg',
      'thumbs/khao sok/imgi_96_DSC01367.jpg',
    ],
    url: 'khao-sok.html'
  },
  {
    title: 'Venice Beach',
    location: 'California, USA',
    year: 2025,
    label: 'Venice Beach, California',
    x: (-118.47 + 180) / 360, y: (90 - 33.98) / 180,
    thumb: 'thumbs/venice beach surf/mainArtboard 2_8.webp',
    canvas: 'canvas/surf.webp',
    images: [
      'thumbs/venice beach surf/imgi_61_surf.jpg',
      'thumbs/venice beach surf/imgi_67_DSC_5893.jpg',
      'thumbs/venice beach surf/imgi_72_DSC_5900.jpg',
      'thumbs/venice beach surf/imgi_79_surf-199.jpg',
      'thumbs/venice beach surf/imgi_84_surf-203.jpg',
      'thumbs/venice beach surf/imgi_91_surf-197.jpg',
    ],
    photos: [
      'thumbs/venice beach surf/imgi_61_surf.jpg',
      'thumbs/venice beach surf/imgi_67_DSC_5893.jpg',
      'thumbs/venice beach surf/imgi_72_DSC_5900.jpg',
      'thumbs/venice beach surf/imgi_79_surf-199.jpg',
      'thumbs/venice beach surf/imgi_84_surf-203.jpg',
      'thumbs/venice beach surf/imgi_91_surf-197.jpg',
      'thumbs/venice beach surf/imgi_97_surf-192.jpg',
      'thumbs/venice beach surf/imgi_102_surf-174.jpg',
      'thumbs/venice beach surf/imgi_108_surf-188.jpg',
      'thumbs/venice beach surf/imgi_115_DSC_6836.jpg',
      'thumbs/venice beach surf/imgi_121_surf-157.jpg',
      'thumbs/venice beach surf/imgi_126_surf-156.jpg',
      'thumbs/venice beach surf/imgi_134_surf-155.jpg',
      'thumbs/venice beach surf/imgi_140_surf-153.jpg',
      'thumbs/venice beach surf/imgi_146_surf-136.jpg',
      'thumbs/venice beach surf/imgi_152_surf-125.jpg',
      'thumbs/venice beach surf/imgi_158_surf-123.jpg',
      'thumbs/venice beach surf/imgi_165_surf-112.jpg',
      'thumbs/venice beach surf/imgi_171_surf-117.jpg',
      'thumbs/venice beach surf/imgi_177_surf-111.jpg',
      'thumbs/venice beach surf/imgi_183_surf-3.jpg',
      'thumbs/venice beach surf/imgi_189_surf-4.jpg',
      'thumbs/venice beach surf/imgi_195_surf-2.jpg',
      'thumbs/venice beach surf/imgi_201_surf-61.jpg',
      'thumbs/venice beach surf/imgi_207_surf-35.jpg',
      'thumbs/venice beach surf/imgi_213_surf-17.jpg',
      'thumbs/venice beach surf/imgi_218_DSC_5957.jpg',
      'thumbs/venice beach surf/imgi_225_DSC_6016.jpg',
    ],
    url: '#'
  },
  {
    title: 'Yosemite',
    location: 'California, USA',
    year: 2022,
    label: 'Yosemite National Park',
    x: (-119.5 + 180) / 360, y: (90 - 37.7) / 180,
    thumb: 'thumbs/yosemite/mainArtboard 2_3.webp',
    canvas: 'canvas/yosemite.webp',
    hideCanvas: true,
    images: [
      'thumbs/yosemite/imgi_23_13-full.jpg',
      'thumbs/yosemite/imgi_28_4-full.jpg',
      'thumbs/yosemite/imgi_35_1-full.jpg',
      'thumbs/yosemite/imgi_42_2-full.jpg',
      'thumbs/yosemite/imgi_49_10-full.jpg',
      'thumbs/yosemite/imgi_56_11-full.jpg',
    ],
    photos: [
      'thumbs/yosemite/imgi_23_13-full.jpg',
      'thumbs/yosemite/imgi_28_4-full.jpg',
      'thumbs/yosemite/imgi_35_1-full.jpg',
      'thumbs/yosemite/imgi_42_2-full.jpg',
      'thumbs/yosemite/imgi_49_10-full.jpg',
      'thumbs/yosemite/imgi_56_11-full.jpg',
      'thumbs/yosemite/imgi_63_3-full.jpg',
      'thumbs/yosemite/imgi_71_6-full.jpg',
      'thumbs/yosemite/imgi_77_5-full.jpg',
      'thumbs/yosemite/imgi_84_15-full.jpg',
      'thumbs/yosemite/imgi_91_9-full.jpg',
      'thumbs/yosemite/imgi_98_7-full.jpg',
      'thumbs/yosemite/imgi_105_14-full.jpg',
      'thumbs/yosemite/imgi_112_12-full.jpg',
      'thumbs/yosemite/imgi_119_8-full.jpg',
    ],
    url: '#'
  }
];

// Photos that appear only on canvas.html — not in library, map, or anywhere else.
// Only needs: title, location, year, canvas (image path), url
const CANVAS_ONLY = [
  // {                                         
  //   title: 'Barcelona',                
  //   location: 'Spain',
  //   year: 2018,                                                                                                                                                                 
  //   canvas: 'canvas/spain.png',   
  //   url: '#'                                                                                                                                                                    
  // },      
  {                                         
    title: 'Jumbo Rocks',                
    location: 'Joshua Tree',
    year: 2020,                                                                                                                                                                 
    canvas: 'canvas/j-tree.png',   
    url: '#'                                                                                                                                                                    
  },    
  {                                         
    title: 'Trees - Long Exposure',                
    location: 'My Front Yard',
    year: 2020,                                                                                                                                                                 
    canvas: 'canvas/long-exposure.png',   
    url: '#'                                                                                                                                                                    
  },    
  {                                         
    title: 'Flowers on Film',                
    location: 'Not Sure',
    year: null,                                                                                                                                                                 
    canvas: 'canvas/film-tulips.png',   
    url: '#'                                                                                                                                                                    
  },     
  {                                         
    title: 'Leaves',                
    location: 'Barcelona, Spain',
    year: 2018,                                                                                                                                                                 
    canvas: 'canvas/spain-leaves.png',   
    url: '#'                                                                                                                                                                    
  },      
  // {                                         
  //   title: 'Little Yellow Flowers',                
  //   location: 'Not Sure',
  //   year: null,                                                                                                                                                                 
  //   canvas: 'canvas/flowers.png',   
  //   url: '#'                                                                                                                                                                    
  // },      
  {                                         
    title: 'Hand',                
    location: 'Dantes Point, Death Valley',
    year: null,                                                                                                                                                                 
    canvas: 'canvas/dantes-point.png',   
    url: '#'                                                                                                                                                                    
  },      
  {                                         
    title: 'Road',                
    location: 'Death Valley',
    year: null,                                                                                                                                                                 
    canvas: 'canvas/death-valley.png',   
    url: '#'                                                                                                                                                                    
  },   
  {                                         
    title: 'Eclipse',                
    location: 'Idaho',
    year: 2017,                                                                                                                                                                 
    canvas: 'canvas/idaho-eclipse.png',   
    url: '#'                                                                                                                                                                    
  },                                                                                                                                                                            
];

// Sort most-recent first; entries with null year fall to the bottom.
PHOTOS.sort((a, b) => {
  if (a.year === null && b.year === null) return 0;
  if (a.year === null) return 1;
  if (b.year === null) return -1;
  return b.year - a.year;
});
